# General Overview

**How many restaurants are in the dataset?**

**How many cities are included?**

**What are the types of restaurants (Cafe, Casual Dining, Quick Bites, etc.)?**

**How many restaurants provide online delivery?**

# 2️⃣ Ratings Analysis

**What is the distribution of ratings? (Histogram / KDE)**

**Which are the top 10 highest-rated restaurants?**

**Which city has the highest average rating?**

**How are ratings related to restaurant type?**

**Are there restaurants with zero ratings?**

# 3️⃣ Cuisine Analysis

**What are the most common cuisines?**

**Which cuisines have the highest average ratings?**

**Which cuisines are most expensive on average?**

**How many cuisines are offered in each city?**

# 4️⃣ Cost Analysis

**What is the distribution of average cost for two people**

**Which city has the most expensive restaurants?**

**Does a higher price mean higher rating? (Scatter plot)**

**Which cuisine types are cheaper or more expensive?**

# 5️⃣ Votes / Popularity Analysis

**Which restaurants received the most votes?**

**Which city has restaurants with the most votes?**

**Is there a relationship between votes and rating?**

# 6️⃣ Online Delivery Analysis

**How many restaurants offer online delivery vs not? (Count plot)**

**Which cities have most restaurants with online delivery?**

**Which cuisines are mostly offered for online delivery?**

# Import Libraries

In [6]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
import plotly.express as px
import statistics as sts

In [7]:
from scipy.stats import kurtosis, norm

In [11]:
df  = pd.read_csv(r"C:\Users\lenovo\Downloads\Zomato data .csv", encoding='latin1')

# Explore Dataset

In [12]:
df

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
...,...,...,...,...,...,...,...
143,Melting Melodies,No,No,3.3/5,0,100,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
146,Darbar,No,No,3.0/5,98,800,Dining
147,Vijayalakshmi,Yes,No,3.9/5,47,200,Dining

In [13]:
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet

In [15]:
df.tail()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
143,Melting Melodies,No,No,3.3/5,0,100,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
146,Darbar,No,No,3.0/5,98,800,Dining
147,Vijayalakshmi,Yes,No,3.9/5,47,200,Dining

In [14]:
q=df['Average Cost for two']
print(q)

KeyError: 'Average Cost for two'

In [ ]:
df.columns

In [ ]:
df['Average Cost for two'].describe()

In [ ]:
df.info()

In [ ]:
df.shape

In [ ]:
df.isna().sum() #cuisine have 9 null values

In [ ]:
df['Restaurant Name'].duplicated().sum()

In [ ]:
#To calculate how many resturants are there 
df['Restaurant Name'].nunique()

In [ ]:
#to calculate how many cities are there
df['City'].nunique()

In [ ]:
# to check all restaurant 
# for i in df['Restaurant Name'].unique():
#     print(i)

In [ ]:
df.head(2)

In [ ]:
(df['Has Online delivery']=='Yes').sum()

In [ ]:
df.head(3)

In [ ]:
sns.set(style='whitegrid')
sns.histplot(df['Aggregate rating'] , kde= True , bins= 20 , color = 'red' , edgecolor='black')
plt.title("distribution of rating data")
plt.xlabel('values')
plt.ylabel('frequency')
plt.show()

In [ ]:
(df['Aggregate rating']==0).sum()

In [ ]:
top10 = df.sort_values(by='Aggregate rating', ascending=False)['Restaurant Name'].head(1)
print(top10)

In [ ]:
#if we want only restaurant Name then

In [ ]:
top10 = df.sort_values(by='Aggregate rating', ascending=False).head(10).reset_index()
print(top10['Restaurant Name'])

In [ ]:
#city which have highest average  rating
df['City'].nunique()

In [ ]:
df['Aggregate rating'].mean()

In [ ]:
# How are ratings related to restaurant type?
df.corr(numeric_only=True)

In [ ]:
# What are the most common cuisines?
df.head(2)

In [ ]:
#as we have previously checked there were some null values in the cuisines 
df.dropna(subset=['Cuisines'], inplace=True)

In [ ]:
df

In [ ]:
city_avg_rating = (
    df.groupby('City')['Aggregate rating']
    .mean()
    .sort_values(ascending=False)
)

print(city_avg_rating.head(10))

means inner city has the highest average rating

In [ ]:
plt.figure(figsize=(6,6))

# Get top 10 cuisines
gb = df['Cuisines'].value_counts().head(10)

# Plot pie chart
plt.pie(gb, labels=gb.index, autopct='%1.2f%%', startangle=90)
plt.title("Top 10 Cuisines by Percentage", fontsize=12)
plt.show()

northindian cuisines is most common

In [ ]:
# Which cuisines have the highest average ratings?
cus_highrating = df.groupby('Cuisines')['Aggregate rating'].mean().sort_values(ascending=False).head(1)
print(cus_highrating)

In [ ]:
# Which cuisines are mostly offered for online delivery?

In [ ]:
# Which cities have most restaurants with online delivery?
a = df.loc[df['Has Online delivery']=='Yes',['Restaurant Name','City']  ]
a

In [ ]:
a.groupby('City').size().sort_values(ascending=False).head(1)

In [ ]:
# Which cuisines are mostly offered for online delivery?
b=df.loc[df['Has Online delivery']=='Yes', ['Cuisines']]

In [ ]:
b.groupby('Cuisines').size().sort_values(ascending=False).head(1)

In [ ]:
df[df['Has Online delivery']=='Yes']['Cuisines'].value_counts().idxmax()

In [ ]:
#Display the values on th bars
import seaborn as sns
import matplotlib.pyplot as plt
a=sns.countplot(x='Has Online delivery', data=df )
values=df['Has Online delivery'].value_counts().values
for i,value in enumerate(values):
  plt.text(i,value+2 , str(value),ha='center', fontweight='bold', color='black')
plt.show()

In [ ]:
plt.figure(figsize=(6,4))
a = sns.countplot(y='Has Online delivery', data=df, palette='viridis')

# Add labels on bars
for container in a.containers:
    a.bar_label(container)

plt.title('Number of Restaurants Having Online Delivery or Not', fontsize=12)
plt.xlabel('Count')
plt.ylabel('Has Online Delivery')
plt.show()